### PR TITLE
Dockerize the application

### PR DESCRIPTION
**Pull request by DevNinja5**
Created a dockerfile
Updated README.md

### CODE REVIEW

**Comment by DevNinja5** [comment]
@AmruthPillai Check this PR. I have dockerized your application.

**Comment by nickspaargaren** [comment]
Why did you delete[ .env.example](https://github.com/AmruthPillai/ResumeOnTheWeb-Gatsby/pull/8/files#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8c)? The variables are still required in [gatsby-config.js](https://github.com/AmruthPillai/ResumeOnTheWeb-Gatsby/blob/master/gatsby-config.js)!

**Comment by DevNinja5** [comment]
@nickspaargaren I think I accidentally deleted that file. Lemme fix it.

**Comment by DevNinja5** [comment]
It's done.

**Pull request merged**
